name=PTSolns_I2Connect_ICP_20100
version=1.0.0
author=PTSolns
maintainer=PTSolns <support@ptsolns.com>
sentence=Library for the PTSolns I2Connect ICP-20100 barometric pressure and temperature module.
paragraph=Provides a streamlined interface to read high-accuracy barometric pressure and temperature data, utilize onboard FIFO buffers, and configure hardware interrupts for the ICP-20100 sensor using I2C.
category=Sensors
url=https://github.com/PTSolns/I2Connect_ICP-20100
architectures=*
includes=PTSolns_I2Connect_ICP_20100.h
